/*
 * AboutBox.java
 *
 * Created on January 6, 2009, 2:23 PM
 */

package com.isf.app.view.containers;

/**
 * @author IN030223
 */
public class AboutBox extends javax.swing.JDialog {

    /**
     * Creates new form AboutBox
     */
    public AboutBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblApp = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblVendor = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblCopy = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblAppText = new javax.swing.JLabel();
        lblVersionText = new javax.swing.JLabel();
        lblVendorText = new javax.swing.JLabel();
        lblHomeText = new javax.swing.JLabel();
        lblCopyText = new javax.swing.JLabel();
        lblDescText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("aboutBox"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblApp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblApp.setText("Application Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblApp, gridBagConstraints);

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/isf.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblIcon, gridBagConstraints);

        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVersion.setText("Version:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblVersion, gridBagConstraints);

        lblVendor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVendor.setText("Vendor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        getContentPane().add(lblVendor, gridBagConstraints);

        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHome.setText("HomePage:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblHome, gridBagConstraints);

        lblCopy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCopy.setText("Copyright:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblCopy, gridBagConstraints);

        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDesc.setText("Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblDesc, gridBagConstraints);

        lblAppText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAppText.setText("Inscriptifact Standalone RTI Viewer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 2.5;
        gridBagConstraints.weighty = 2.5;
        getContentPane().add(lblAppText, gridBagConstraints);

        lblVersionText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVersionText.setText("1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 2.5;
        gridBagConstraints.weighty = 2.5;
        getContentPane().add(lblVersionText, gridBagConstraints);

        lblVendorText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVendorText.setText("WSR Project, USC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 2.5;
        gridBagConstraints.weighty = 2.5;
        getContentPane().add(lblVendorText, gridBagConstraints);

        lblHomeText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHomeText.setText("www.inscriptifact.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 2.5;
        gridBagConstraints.weighty = 2.5;
        getContentPane().add(lblHomeText, gridBagConstraints);

        lblCopyText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCopyText.setText("© 2007 - 2009 University Of Southern California");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 2.5;
        gridBagConstraints.weighty = 2.5;
        getContentPane().add(lblCopyText, gridBagConstraints);

        lblDescText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescText.setText("A standalone viewer for visualizing Polynomial Texture Mapping (PTM) files both of the RGB and LRGB formats.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 3.0;
        getContentPane().add(lblDescText, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblApp;
    private javax.swing.JLabel lblAppText;
    private javax.swing.JLabel lblCopy;
    private javax.swing.JLabel lblCopyText;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDescText;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHomeText;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblVendor;
    private javax.swing.JLabel lblVendorText;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JLabel lblVersionText;
    // End of variables declaration//GEN-END:variables

}
